# Generated by Django 3.0.5 on 2023-09-04 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientID', models.PositiveIntegerField()),
                ('consultantID', models.PositiveIntegerField()),
                ('clientName', models.CharField(max_length=40, null=True)),
                ('consultantName', models.CharField(max_length=40, null=True)),
                ('appiontmentRequestCategory', models.CharField(choices=[('Dating', 'Dating'), ('Relationships', 'Relationships'), ('Breakups', 'Breakups'), ('Divorce', 'Divorce'), ('Marriage', 'Marriage'), ('Family', 'Family'), ('Business', 'Business')], max_length=100)),
                ('appointmentDate', models.DateField(auto_now=True)),
                ('description', models.TextField(max_length=500)),
                ('status', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientDischargeDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientId', models.PositiveIntegerField()),
                ('clientName', models.CharField(max_length=40)),
                ('assignedconsultantName', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=40)),
                ('appiontmentRequestCategory', models.CharField(choices=[('Dating', 'Dating'), ('Relationships', 'Relationships'), ('Breakups', 'Breakups'), ('Divorce', 'Divorce'), ('Marriage', 'Marriage'), ('Family', 'Family'), ('Business', 'Business')], max_length=100)),
                ('consultationRequestDate', models.DateField()),
                ('consultationReleaseDate', models.DateField()),
                ('consultancyFee', models.PositiveIntegerField()),
                ('consultantFee', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ClientPrescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientId', models.PositiveIntegerField()),
                ('clientName', models.CharField(max_length=40)),
                ('assignedconsultantName', models.CharField(max_length=40)),
                ('appiontmentRequestCategory', models.CharField(choices=[('Dating', 'Dating'), ('Relationships', 'Relationships'), ('Breakups', 'Breakups'), ('Divorce', 'Divorce'), ('Marriage', 'Marriage'), ('Family', 'Family'), ('Business', 'Business')], max_length=100)),
                ('presscription', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConsultancyCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ConsultancyService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('serviceDescripton', models.TextField()),
                ('serviceRate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability', models.CharField(max_length=100)),
                ('serviceCaption', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reciever', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recieved_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestMesssage', models.TextField()),
                ('requestStatus', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_client', to=settings.AUTH_USER_MODEL)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_consultant', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.ConsultancyService')),
            ],
        ),
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilePicture', models.ImageField(blank=True, null=True, upload_to='profilePics/')),
                ('address', models.CharField(blank=True, max_length=40, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=12, null=True)),
                ('mobile', models.CharField(blank=True, max_length=40, null=True)),
                ('consultantcyServiceSpeciality', models.CharField(choices=[('Dating', 'Dating'), ('Relationships', 'Relationships'), ('Breakups', 'Breakups'), ('Divorce', 'Divorce'), ('Marriage', 'Marriage'), ('Family', 'Family'), ('Business', 'Business')], max_length=50)),
                ('availability_status', models.BooleanField(default=False)),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultant_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilePicture', models.ImageField(blank=True, null=True, upload_to='profilePics/')),
                ('address', models.CharField(blank=True, max_length=40, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=12, null=True)),
                ('mobile', models.CharField(blank=True, max_length=40, null=True)),
                ('siteRegisterDate', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('assignedConsultantID', models.PositiveIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
