# Generated by Django 4.2.3 on 2023-09-04 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_remove_client_address_remove_client_mobile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdischargedetails',
            name='address',
        ),
    ]
