# Generated by Django 4.2.3 on 2023-08-10 19:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('baseapp', '0003_consultationrequest_created_at_notification_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Profile',
        ),
        migrations.RenameModel(
            old_name='ConsultancyService',
            new_name='Service',
        ),
    ]
