# Generated by Django 4.2.3 on 2023-08-10 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0004_rename_userprofile_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.profile'),
        ),
    ]
