# Generated by Django 4.2.3 on 2023-08-11 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0005_alter_service_consultant'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='ConsultancyService',
        ),
    ]
