# Generated by Django 4.2.3 on 2023-08-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0008_alter_notification_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultancyservice',
            name='serviceCaption',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='requestStatus',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
    ]
