# Generated by Django 4.1.3 on 2023-08-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0009_consultancyservice_servicecaption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrequest',
            name='requestMesssage',
            field=models.TextField(blank=True, null=True),
        ),
    ]
